import type { ReportMeta } from '../model';
import { Section } from '../components/Section';
import { fmtDate, fmtDateRange } from '../format';

/**
 * Section 1 — the cover. Title, site, generation date, the data window, the
 * producing tool, and a confidentiality line (docs/REPORT_SPEC.md §Structure).
 */
export function CoverSection({ meta }: { meta: ReportMeta }) {
  return (
    <Section title={meta.title} site={meta.site_name} cover>
      <div className="flex flex-col" style={{ minHeight: '7in' }}>
        <div className="flex-1 flex flex-col justify-center">
          <div
            className="t-label mb-4"
            style={{ color: 'var(--accent)', letterSpacing: '0.08em', textTransform: 'uppercase' }}
          >
            {meta.tool} · Network assessment
          </div>

          <h1
            style={{
              fontSize: 40,
              lineHeight: '46px',
              fontWeight: 600,
              letterSpacing: '-0.02em',
              color: 'var(--fg)',
              maxWidth: '9rem',
            }}
          >
            {meta.title}
          </h1>

          <div className="t-section mt-3" style={{ color: 'var(--fg-muted)', fontWeight: 500 }}>
            {meta.site_name}
          </div>

          <dl className="mt-10 grid gap-y-3" style={{ gridTemplateColumns: 'auto 1fr', columnGap: 32 }}>
            <CoverRow label="Report date" value={fmtDate(meta.generated_ts)} />
            <CoverRow
              label="Data window"
              value={`${fmtDateRange(meta.window.start_ts, meta.window.end_ts)} · ${meta.window.label}`}
            />
            <CoverRow
              label="Generated by"
              value={`${meta.tool}${meta.tool_version ? ` ${meta.tool_version}` : ''}`}
            />
          </dl>
        </div>

        <div
          className="mt-8 pt-4 t-caption"
          style={{ borderTop: '1px solid var(--hairline)', color: 'var(--fg-subtle)', maxWidth: '42rem' }}
        >
          {meta.confidentiality}
        </div>
      </div>
    </Section>
  );
}

function CoverRow({ label, value }: { label: string; value: string }) {
  return (
    <>
      <dt className="t-label" style={{ color: 'var(--fg-subtle)' }}>
        {label}
      </dt>
      <dd className="t-body tnum" style={{ color: 'var(--fg)', margin: 0 }}>
        {value}
      </dd>
    </>
  );
}
